[package]
name = "rls"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = {version = "4.5.9", features=["derive"]}
inline_colorization = "0.1.6"
nix = {version = "0.29.0", features = ["user"]}
prettytable = "0.10.0"
term_size = "0.3.2"
