[tasks.prepare-coverage]
script_runner = "@duckscript"
script = ["mkdir target/llvm-cov"]

[tasks.test]
# this needs the crates 'nextest' and 'cargo-llvm-cov' installed locally
dependencies = ["prepare-coverage"]
command = "cargo"
args = [
  "llvm-cov",
  "nextest",
  "--no-fail-fast",
  "--lcov",
  "--output-path=target/llvm-cov/coverage.lcov",
]

[tasks.test-html]
command = "cargo"
args = ["llvm-cov", "nextest", "--html"]

[tasks.audit]
command = "cargo"
args = ["audit"]

[tasks.deny]
command = "cargo"
args = ["deny", "check"]
