name: Build Docs 

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'docs/**' # only need this to run if changes to the actual docs
  workflow_dispatch:

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  build:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to publish the gh-pages branch.

    steps:
      - name: Monitor GitHub token permissions
        if: runner.os != 'Windows'
        uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install mdBook
        run: cargo install mdbook

      - name: Build the book
        run: mdbook build docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ github.token }}
          publish_dir: ./docs/book
          publish_branch: gh-pages
