name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  unix:
    runs-on: ubuntu-latest

    steps:
      - name: Monitor GitHub token permissions
        if: runner.os != 'Windows'
        uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-targets --all-features

  windows:
    runs-on: windows-latest

    steps:
      - name: Monitor GitHub token permissions
        if: runner.os != 'Windows'
        uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-targets --all-features

  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Monitor GitHub token permissions
        if: runner.os != 'Windows'
        uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make,cargo-audit

      - name: Run cargo-audit
        run: cargo make audit

  deny:
    runs-on: ubuntu-latest

    steps:
      - name: Monitor GitHub token permissions
        if: runner.os != 'Windows'
        uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make,cargo-deny

      - name: Run cargo-deny
        run: cargo make deny
